! Generated by cart. DO NOT EDIT
program main
    implicit none

    if (.not.run()) stop 1
contains
    function run() result(passed)
        use lcg_test, only: &
                lcg_lcg => &
                    test_lcg
        use sm_test, only: &
                sm_sm => &
                    test_sm
        use veggies, only: test_item_t, test_that, run_tests



        logical :: passed

        type(test_item_t) :: tests
        type(test_item_t) :: individual_tests(2)

        individual_tests(1) = lcg_lcg()
        individual_tests(2) = sm_sm()
        tests = test_that(individual_tests)


        passed = run_tests(tests)

    end function
end program
