stages:
  - test
  - documentation
  - pages

test:
  stage: test
  image: registry.gitlab.com/everythingfunctional/dockerfpm
  script:
    - fpm build # TODO: use dieharder to test various implementations

documentation:
  stage: documentation
  image: python
  script:
    - pip install ford
    - apt update && apt install -y graphviz gfortran
    - ford doc/front-matter.md
  artifacts:
    paths:
      - public

pages:
  stage: pages
  dependencies:
    - documentation
  script:
    - echo "Deploying to pages"
  artifacts:
    paths:
      - public
  only:
    - main
