name = "rngff"
version = "0.1.1"
license = "MIT"
author = "Brad Richardson"
maintainer = "everythingfunctional@protonmail.com"
copyright = "Copyright 2022, Brad Richardson"

[dev-dependencies]
veggies = { git = "https://gitlab.com/everythingfunctional/veggies.git", tag = "v1.0.5" }
prune = { git = "https://gitlab.com/everythingfunctional/prune.git", tag = "v0.1.5" }
iso_varying_string = { git = "https://gitlab.com/everythingfunctional/iso_varying_string.git", tag = "v3.0.3" }
strff = { git = "https://gitlab.com/everythingfunctional/strff.git", tag = "v4.0.0" }

[[executable]]
name="lcg_64bit_stream"
source-dir="app"
main="lcg_64bit_stream.f90"

[[executable]]
name="sm_64bit_stream"
source-dir="app"
main="sm_64bit_stream.f90"

[[executable]]
name="lcg_32bit_stream"
source-dir="app"
main="lcg_32bit_stream.f90"